version: '3.8'

services:
  # Microservicio 1: user_microservice
  user-service:
    build:
      context: ./backend/user_microservice
      dockerfile: Dockerfile
    container_name: user_microservice-container
    ports:
      - "8001:8000"
    environment:
      DB_HOST: 172.31.95.13   # IP de la MV de BD
      DB_PORT: 8005           # Puerto expuesto de MySQL
      DB_NAME: user_db
      DB_USER: user
      DB_PASSWORD: userpassword
    networks:
      - backend

  # Microservicio 2: content-service
  content-service:
    build:
      context: ./backend/content_microservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.31.95.13:8006/video-db  # Cambiado puerto
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresql
    networks:
      - backend

  # Microservicio 3: historial-service (Node + MongoDB)
  historial-service:
    build:
      context: ./backend/historial-service
      dockerfile: Dockerfile
    container_name: historial-service-container
    ports:
      - "3001:3000"
    environment:
      MONGODB_URI: mongodb://172.31.95.13:27017/historial_db
    networks:
      - backend

  # Microservicio 4: orchestrator
  orchestrator:
    build: ./backend/orchestrator
    container_name: orchestrator-service
    ports:
      - "9000:9000"
    environment:
      USER_SERVICE_URL: "http://user-service:8000/user"
      CONTENT_SERVICE_URL: "http://content-service:8080/video"
      HISTORY_SERVICE_URL: "http://historial-service:3000/historial"
    networks:
      - backend

networks:
  backend:
    driver: bridge
