version: '3.8'

services:
  # Microservicio 1: user_microservice
  user-service:
    build:
      context: ./backend/user_microservice
      dockerfile: Dockerfile
    container_name: user_microservice-container
    ports:
      - "8001:8000"  
    depends_on:
      - mysql 
    environment:
      DB_HOST: 172.31.95.13  
      DB_PORT: 8005
      DB_NAME: user_db
      DB_USER: user
      DB_PASSWORD: userpassword
    networks:
      - backend

  content-service:
    build:
      context: ./backend/content_microservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.31.95.13:5432/video-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgresql
    networks:
      - backend

  # Historial Microservice (Node + Mongo)
  historial-service:
    build:
      context: ./backend/historial-service
      dockerfile: Dockerfile
    container_name: historial-service-container
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://172.31.95.13:27017/historial_db
    networks:
      - backend

  orchestrator:
    build: ./backend/orchestrator
    container_name: orchestrator-service
    ports:
      - "9000:9000"
    environment:
      USER_SERVICE_URL: "http://user-service:8000/user"
      CONTENT_SERVICE_URL: "http://content-service:8080/video"
      HISTORY_SERVICE_URL: "http://historial-service:3000/historial"
    networks:
      - backend


networks:
  backend:
    driver: bridge